name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinxjp.themes.gopher
    - name: Build sphinx
      run: make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./python-tokai-41/build/html
        force_orphan: true
